// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LivrariaControleEmprestimo.DATA.Models
{
    public partial class Cliente
    {
        public Cliente()
        {
            LivroClienteEmprestimo = new HashSet<LivroClienteEmprestimo>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("CPF")]
        [StringLength(14)]
        [DisplayName("CPF")]
        [Unicode(false)]
        public string Cpf { get; set; }
        [Column("nome")]
        [StringLength(100)]
        [DisplayName("Nome Completo")]
        [Unicode(false)]
        public string Nome { get; set; }
        [Column("logradouro")]
        [StringLength(50)]
        [DisplayName("Logradouro")]
        [Unicode(false)]
        public string Logradouro { get; set; }
        [Column("cidade")]
        [StringLength(50)]
        [DisplayName("Cidade")]
        [Unicode(false)]
        public string Cidade { get; set; }
        [Column("bairro")]
        [StringLength(50)]
        [DisplayName("Bairro")]
        [Unicode(false)]
        public string Bairro { get; set; }
        [Column("estado")]
        [StringLength(50)]
        [DisplayName("Estado")]
        [Unicode(false)]
        public string Estado { get; set; }
        [Column("telefone")]
        [DisplayName("Telefone")]
        public int? Telefone { get; set; }

        [Column("Cep")]
        [DisplayName("CEP")]
        public int? Cep { get; set; }
        [Column("numero")]
        [DisplayName("Nº")]
        public int? Numero { get; set; }
        [Column("ddd")]
        [DisplayName("DDD")]
        public int? Ddd { get; set; }

        [InverseProperty("IdClienteNavigation")]
        public virtual ICollection<LivroClienteEmprestimo> LivroClienteEmprestimo { get; set; }
    }
}